# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cx < Formula
  desc "CX — AI-native project knowledge system"
  homepage "https://github.com/AngelMaldonado/cx"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.2.0/cx_0.2.0_darwin_amd64.tar.gz"
      sha256 "b6a7f1f7ce52217af8d4f37135e2abda7a985a8576b0bda1a5f3588ab9e9035c"

      define_method(:install) do
        bin.install "cx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.2.0/cx_0.2.0_darwin_arm64.tar.gz"
      sha256 "b00299b43cdbcda0851ee3be2d55869505b13a555b2ad328210f86c1950301fb"

      define_method(:install) do
        bin.install "cx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.2.0/cx_0.2.0_linux_amd64.tar.gz"
      sha256 "0b71f2f0e9835100c011e9c0c69e99face3f5020fef38af1ed5340d530db255a"
      define_method(:install) do
        bin.install "cx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.2.0/cx_0.2.0_linux_arm64.tar.gz"
      sha256 "4cd09c4765b08378176ece89097c54208a2334f30c64eeeb2a7e1edcc915a876"
      define_method(:install) do
        bin.install "cx"
      end
    end
  end

  test do
    system "#{bin}/cx", "--version"
  end
end
