# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cx < Formula
  desc "CX — AI-native project knowledge system"
  homepage "https://github.com/AngelMaldonado/cx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.1.0/cx_0.1.0_darwin_amd64.tar.gz"
      sha256 "b9cd48670adc4ce959d94e3d5bd31cb59f9fd98dd1a3d04b7efeda2c9b45e638"

      define_method(:install) do
        bin.install "cx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.1.0/cx_0.1.0_darwin_arm64.tar.gz"
      sha256 "b307afa7a2b268bd5ee957b4d050450d4e6594dc507b314024134ba0bbf50940"

      define_method(:install) do
        bin.install "cx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.1.0/cx_0.1.0_linux_amd64.tar.gz"
      sha256 "83c8affe0eb4af60f847b293662c8963780110433dfc4b2a3b863b78254395a8"
      define_method(:install) do
        bin.install "cx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AngelMaldonado/cx/releases/download/v0.1.0/cx_0.1.0_linux_arm64.tar.gz"
      sha256 "e0e2f3fe68b8a0b7f0b3a0c8a6f0d687e2de40e1ab75f370a30ae56caf638c32"
      define_method(:install) do
        bin.install "cx"
      end
    end
  end

  test do
    system "#{bin}/cx", "--version"
  end
end
