package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/AngelMaldonado/cx/internal/agents"
	"github.com/AngelMaldonado/cx/internal/project"
	"github.com/spf13/cobra"
)

var disableCmd = &cobra.Command{
	Use:   "disable",
	Short: "Suspend cx across all projects",
	RunE:  runDisable,
}

const disabledStub = "<!-- cx disabled — run `cx enable` to restore. Do not edit this file while cx is disabled. -->\n"

func runDisable(cmd *cobra.Command, args []string) error {
	if project.IsDisabled() {
		fmt.Println("cx is already disabled.")
		return nil
	}

	registry, err := project.LoadRegistry()
	if err != nil {
		return err
	}

	backedUp := 0
	for _, path := range registry.Projects {
		installedAgents := agents.DetectInstalled(path)
		for _, agent := range installedAgents {
			configFilePath := filepath.Join(path, agent.ConfigFile)
			content, err := os.ReadFile(configFilePath)
			if err != nil {
				if os.IsNotExist(err) {
					continue
				}
				return err
			}
			if err := project.BackupAgentConfig(path, agent.ConfigFile, string(content)); err != nil {
				return err
			}
			if err := os.WriteFile(configFilePath, []byte(disabledStub), 0o644); err != nil {
				return err
			}
			backedUp++
		}
	}

	if err := project.SetDisabled(""); err != nil {
		return err
	}

	fmt.Printf("cx disabled. %d config file(s) backed up.\n", backedUp)
	return nil
}
